spring:
  application:
    name: BookReaderService

server:
  port: 9092

eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

      fetchRegistry: true